const Database = require('better-sqlite3');
const db = new Database('./data/manga.db');

const updates = {
  lang_views: "Okunma",
  lang_status: "Durum",
  lang_type: "Tür",
  lang_author: "Yazar",
  lang_artist: "Çizer",
  lang_first_chapter: "İlk Bölüm",
  lang_latest_chapter: "Son Bölüm",
  lang_chapter_prefix: "Bölüm",
  lang_rating: "Puan",
  lang_genres: "Türler",
  lang_synopsis: "Özet",
  lang_chapter_list: "Bölüm Listesi",
  lang_ongoing: "Devam Ediyor",
  lang_completed: "Tamamlandı",
  lang_hiatus: "Ara Verildi",
  lang_comments: "Yorumlar",
  lang_delete: "Sil",
  lang_report: "Rapor Et",
  lang_no_comments: "Henüz yorum yok. İlk yorumu sen yaz!",
  lang_login_to_comment: "Yorum yazmak için giriş yap",
  lang_bookmark: "Kitaplık",
  lang_share: "Paylaş",
  lang_show_more: "Daha Fazla Göster",
  lang_show_less: "Daha Az Göster",
  lang_search_chapters: "Bölüm Ara...",
  lang_no_synopsis: "Bu seri için henüz özet bulunmuyor.",
  lang_no_chapters: "Henüz bölüm yüklenmemiş.",
  lang_no_chapters_match: "Aramanızla eşleşen bölüm bulunamadı.",
  lang_you_may_also_like: "Bunları da Beğenebilirsiniz",
  lang_list_reading: "Okuyor",
  lang_list_completed: "Tamamlandı",
  lang_list_plan: "Okuma Planı",
  lang_list_dropped: "Bırakıldı",
  lang_series_requests_title: "Seri İstekleri",
  lang_details_btn: "Detay",
  lang_new_badge: "Yeni",
  lang_genres_label: "Türler:",
  // Time terms
  lang_time_just_now: "şimdi",
  lang_time_min_ago: " dakika önce",
  lang_time_hour_ago: " saat önce",
  lang_time_day_ago: " gün önce",
  lang_time_week_ago: " hafta önce",
  lang_time_month_ago: " ay önce",
  lang_announcement_label: "Duyuru",
  lang_stat_series: "Seri",
  lang_stat_chapters: "Bölüm",
  lang_stat_members: "Üye",
  lang_ranking_title: "En İyiler",
  lang_ranking_subtitle: "En çok okunan ve en çok puan alan seriler",
  lang_claiming: "Talep ediliyor...",
  lang_daily_login_hint: "Günlük giriş ödülünü almak için her gün giriş yapın!",
  lang_daily_login_reward_claimed: "Günlük giriş ödülü başarıyla alındı!",
  lang_claimed_today: "Bugünün ödülü zaten alındı",
  lang_you: "Siz",
  lang_no_users_ranking: "Sıralamada henüz kullanıcı bulunuyor.",
  lang_must_be_logged_in: "Ödül almak için giriş yapmalısınız.",
  lang_error_claiming: "Ödül talep edilirken bir hata oluştu.",
  // Sidebar / Header
  lang_most_read: "En Çok Okunanlar",
  lang_editors_pick: "Editörün Seçimi",
  lang_newest: "En Yeni",
  lang_oldest: "En Eski",
  lang_read_now: "Şimdi Oku",
  lang_add_to_list: "Listeye Ekle",
  lang_write_comment: "Yorum Yaz",
  lang_load_more_comments: "Daha Fazla",
  lang_prev_chapter: "Önceki Bölüm",
  lang_next_chapter: "Sonraki Bölüm",
  lang_view_all: "Tümünü Gör",
  lang_trending_right_now: "Şu Anda Trend Olanlar",
  lang_no_views: "Henüz görüntülenme kaydedilmedi.",
  lang_back_to_series: "Seriye Dön",
  lang_settings: "Ayarlar",
  lang_reader_loading: "Yükleniyor...",
  lang_no_chapters_yet: "Henüz bölüm yok",
  lang_trending: "Trend Olanlar",
  lang_search_placeholder: "Ara...",
  lang_login_title: "Giriş Yap",
  lang_register_title: "Kayıt Ol",
  lang_browse_title: "Manga Keşfet",
  lang_browse_subtitle: "Koleksiyonumuzdaki serileri keşfedin",
  lang_all_genres: "Tüm Türler",
  lang_sort_latest: "En Yeni",
  lang_sort_popular: "Popüler",
  lang_sort_rating: "Puan",
  lang_sort_az: "A-Z",
  lang_status_all: "Tümü",
  lang_status_ongoing: "Devam Ediyor",
  lang_status_completed: "Tamamlandı",
  lang_status_hiatus: "Ara Verildi",
  lang_no_results: "Sonuç bulunamadı.",
  lang_load_more: "Daha Fazla Yükle",
  lang_post_comment: "Yorum Gönder",
  lang_spoiler: "Spoiler",
  lang_show_spoiler: "Spoileri Göster",
  lang_replies_label: "Yanıtlar",
  lang_sort_best: "En İyi",
  lang_loading: "Yükleniyor...",
  lang_series_reaction_title: "Tepkiler",
  lang_reactions: "Tepkiler",
  lang_seo_site_tagline: "En İyi Manga Okuma Platformu",
  lang_seo_series_prefix: "Manga Oku",
  lang_seo_home_title: "Ana Sayfa",
  lang_seo_browse_title: "Manga Keşfet",
  lang_seo_ranking_title: "Sıralama",
  lang_reader_settings: "Okuyucu Ayarları",
  lang_image_width: "Resim Genişliği",
  lang_brightness: "Parlaklık",
  lang_theater_mode: "Sinema Modu",
  lang_lights_on: "Işıkları Aç",
  lang_lights_off: "Işıkları Kapat",
  lang_reset: "Sıfırla",
  lang_reset_all: "Tümünü Sıfırla",
  lang_scroll_top: "Yukarı Git",
  lang_comments_label: "Yorumlar",
  lang_series_label: "Seriler",
  lang_next_up: "Sıradaki Bölüm",
  lang_read_chapter: "Bölümü Oku",
  lang_up_to_date: "Güncel",
  lang_no_more_chapters: "Başka bölüm yok",
  lang_browse_more: "Daha Fazla Keşfet",
  lang_chapter_not_found: "Bölüm bulunamadı",
  lang_back_to_browse: "Aramaya Dön",
  lang_no_pages: "Bu bölümün sayfası bulunmuyor",
  lang_keyboard_shortcut_hint: "Bölümler arasında geçiş yapmak için yön tuşlarını kullanabilirsiniz.",
  lang_bookmarked: "Kütüphaneye Eklendi",
  lang_copied: "Kopyalandı!",
  lang_show_all: "Tümünü Göster",
  lang_start_reading: "Okumaya Başla",
  lang_continue_reading: "Okumaya Devam Et",
  lang_load_more_updates: "Daha Fazla Güncelleme"
};

const stmt = db.prepare("INSERT OR REPLACE INTO app_settings (setting_key, setting_value) VALUES (?, ?)");
const transaction = db.transaction(() => {
  for (const [key, value] of Object.entries(updates)) {
    stmt.run(key, value);
  }
  db.prepare("UPDATE app_settings SET setting_value = ? WHERE setting_key = ?").run(
    '[{"label":"Ana Sayfa","url":"/"},{"label":"Manga Keşfet","url":"/series"},{"label":"Sıralama","url":"/ranking"},{"label":"Seri İstekleri","url":"/requests"}]',
    'navbar_menu'
  );
  db.prepare("UPDATE app_settings SET setting_value = ? WHERE setting_key = ?").run(
    '[{"label":"Gizlilik Politikası","url":"/privacy"},{"label":"Kullanım Koşulları","url":"/terms"},{"label":"Manga Keşfet","url":"/series"}]',
    'footer_menu'
  );
});

transaction();

process.exit(0);
