export const metadata = {
  title: 'Terms & Conditions — YomiTranslate',
  description: 'YomiTranslate terms and conditions of use.',
};

export default function TermsPage() {
  return (
    <div className="page-container fade-in" style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 24px 80px' }}>
      <h1 style={{ fontSize: '1.8rem', fontWeight: 800, marginBottom: '8px' }}>Terms & Conditions</h1>
      <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginBottom: '32px' }}>Last updated: March 2026</p>

      <div className="policy-content">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using YomiTranslate, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should not use the service.</p>

        <h2>2. Description of Service</h2>
        <p>YomiTranslate is a manga reading platform that provides AI-powered translation of manga pages into multiple languages using the Torii Translate service. The platform allows users to browse, read, and translate manga content.</p>

        <h2>3. User Accounts</h2>
        <ul>
          <li>You must provide accurate information when creating an account</li>
          <li>You are responsible for maintaining the security of your account credentials</li>
          <li>You must be at least 13 years old to create an account</li>
          <li>One person may not maintain more than one account</li>
        </ul>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Upload content that infringes on intellectual property rights</li>
          <li>Use the service for any illegal or unauthorized purpose</li>
          <li>Attempt to access other users&apos; accounts or private data</li>
          <li>Abuse, harass, or threaten other users through comments or messages</li>
          <li>Overload the service with excessive API requests or automated scraping</li>
          <li>Circumvent any security measures or access restrictions</li>
        </ul>

        <h2>5. Content</h2>
        <p>Users who upload manga content are responsible for ensuring they have the appropriate rights or permissions to do so. YomiTranslate does not claim ownership of user-uploaded content.</p>

        <h2>6. AI Translation</h2>
        <ul>
          <li>Translations are generated by AI and may not be perfectly accurate</li>
          <li>Translation quality may vary depending on the source material</li>
          <li>Translated pages are cached to improve performance and reduce costs</li>
          <li>Translation availability depends on the Torii Translate API service</li>
        </ul>

        <h2>7. Comments & Community</h2>
        <p>Users may post comments on series and chapters. We reserve the right to remove any comments that violate our acceptable use policy. Users can report inappropriate content to the administrators.</p>

        <h2>8. Intellectual Property</h2>
        <p>The YomiTranslate platform, including its design, code, and branding, is the property of its creators. Users retain ownership of content they upload, but grant YomiTranslate a license to display and process that content as part of the service.</p>

        <h2>9. Limitation of Liability</h2>
        <p>YomiTranslate is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from use of the service, including but not limited to data loss, service interruptions, or inaccurate translations.</p>

        <h2>10. Termination</h2>
        <p>We reserve the right to suspend or terminate accounts that violate these terms. Users may delete their account at any time by contacting the administrator.</p>

        <h2>11. Changes to Terms</h2>
        <p>We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>

        <h2>12. Governing Law</h2>
        <p>These terms are governed by applicable laws. Any disputes shall be resolved in the appropriate jurisdiction.</p>

        <h2>13. Contact</h2>
        <p>For questions about these terms, please contact the site administrator.</p>
      </div>
    </div>
  );
}
